### ISSUE TITLE
What's the meaning of the image's name, the last two numbers 01, 02 or 07, 08

### ISSUE THREAD

**Issue by Huixxi** [ox-vgg/vgg_face2#18]
I don't understand how images in vggface2 being labeled, I mean the information of pose and age, how these information being represented from their images' name.

**Comment by WeidiXie** [comment]
Hi, @Huixxi   

the pose, age information is not represented by the name, 

the image name doesn't mean anything, the reason it has numbers is because we detect the faces from images, and the same image might contain multiple person, so that's why it has 01, 02, etc.

and the reason they are discontinuous is because, we deleted the faces that doesn't belong to this identity during the cleaning process.

Best
Weidi
